### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by leonkding** [MathGaron/mean_average_precision#1]
Hi, I am afraid that example didn't show the right result, am I missing something?

**Comment by MathGaron** [comment]
Thank you for your feedback! What do you mean exactly by not showing the right result? 

The image in the README is extracted from another dataset, I will push details about this not to confuse users. I will put an example of the example plot in the repo.
 Although, if you compare with another implementation and they both return different results, just send me the other case so I can make sure that there is no bug in my implementation. Thanks!

**Comment by leonkding** [comment]
seems like the way to calculate mean average precision is wrong, you should choose 11 equally spaced recall levels [0,0.1,...,1], not threshold.

**Comment by MathGaron** [comment]
I will close this issue. if there is anything do not hesitate.
