### ISSUE TITLE
How exactly are multiple detections of same object counted?

### ISSUE THREAD

**Issue by AmitaiPerlstein** [MathGaron/mean_average_precision#19]
ReadME says:

**True positive (TP):
Gt x predicted as x

False positive (FP):
Gt x classified as x more than once**

Say I have two detections of same object.
Will the more confident one be treated as TP while the less confident one as FP (which makes sense)?
Or will all detections of this object be treated as FP (which is what I understand from the ReadME)?

**Comment by MathGaron** [comment]
Hey @AmitaiPerlstein ,

The more confident one will be treated as TP, and other detections will be treated as FP (as seen on the figure) The ReadMe is indeed unclear, I will update it thanks!
Just ask if you have more questions!
