### ISSUE TITLE
README unclear

### ISSUE THREAD

**Issue by qualiaa** [MathGaron/mean_average_precision#20]
In the README, where it says:

* Predicted bounding boxes : numpy array [n, 4]
* Predicted classes: numpy array [n]
* Predicted confidences: numpy array [n]
* Ground truth bounding boxes:numpy array [n, 4]
* Ground truth classes: numpy array [n]

it would be much clearer to use some other variable for the ground truth sizes. I spent a while wondering what n could possibly be shared between the predicted and gt boxes.

**Comment by MathGaron** [comment]
Good point! Thank you, I just fixed it.
