### ISSUE TITLE
Doubt on TP + FN

### ISSUE THREAD

**Issue by alessandro-montanari** [MathGaron/mean_average_precision#5]
Hi,
I am trying to get a better understanding of the mAP and I went through your code. The doubt I am having is about how TP + FN (which represents the ground truth) is computed.
Let's consider the first frame in example.py. There is one bounding box for class "1"  so I would expect to see TP + FN always equal to 1 but if I print all the accumulators for class "1" this is not the case. Often TP and FN are both at zero. This is what I get for the 11 accumulators for class "1":
```
True positives : 0
False positives : 0
False Negatives : 1
Precision : 0
Recall : 0.0

True positives : 0
False positives : 0
False Negatives : 1
Precision : 0
Recall : 0.0

True positives : 0
False positives : 0
False Negatives : 1
Precision : 0
Recall : 0.0

True positives : 0
False positives : 0
False Negatives : 1
Precision : 0
Recall : 0.0

True positives : 0
False positives : 1
False Negatives : 0
Precision : 0.0
Recall : 1

True positives : 0
False positives : 1
False Negatives : 0
Precision : 0.0
Recall : 1

True positives : 0
False positives : 2
False Negatives : 0
Precision : 0.0
Recall : 1

True positives : 0
False positives : 3
False Negatives : 0
Precision : 0.0
Recall : 1

True positives : 0
False positives : 3
False Negatives : 0
Precision : 0.0
Recall : 1

True positives : 0
False positives : 3
False Negatives : 0
Precision : 0.0
Recall : 1

True positives : 0
False positives : 5
False Negatives : 0
Precision : 0.0
Recall : 1
```
Is it correct?
Thanks!

**Comment by MathGaron** [comment]
There is indeed a bug! I will fix this as fast as possible, as this affects the results.
There is a confusion in the current code with the classes, I will rewrite it so it is more explicit that we handle each class as being class vs all other. That should make the code less confusing also.

I will also add unit tests to be able to debug each step independently, it will help readability.
I should be able to get this before Monday ( I really need to fix this!)

Once again thank you, and sorry about that!

**Comment by MathGaron** [comment]
There is indeed a bug! I will fix this as soon as possible, as this affects the results.
There is a confusion in the current code with the classes, I will rewrite it so it is more explicit that we handle each class as being class vs all other. That should also make the code less confusing.

I will also add unit tests to be able to debug each step independently, it will help readability.
I should be able to get this before Monday.

Once again thank you, and sorry about that!

**Comment by MathGaron** [comment]
There is indeed a bug, seems like that the threshold affects the False negative computation. I will fix this as soon as possible, as this affects the results.

There is a confusion in the current code with the classes, I will rewrite it so it is more explicit that we handle each class as being class vs all other. That should make the code less confusing also.

I will also add unit tests to be able to debug each step independently, it will help readability.
I should be able to get this before Monday.

Once again thank you, and sorry about that!

**Comment by alessandro-montanari** [comment]
Thanks! I might also have a closer look at it this weekend.

**Comment by MathGaron** [comment]
Once again, your help is really appreciated, I will make a Wiki with figures to explain what the algorithm does, this way the method will be transparent and may help people to wrap their mind around this! Because indeed it can get confusing!

**Comment by MathGaron** [comment]
I just pushed a fix. Added unit tests to debug each component. I will add more info to the readme shortly. I will wait your feedback to consider this closed

I also found another issue with false positive computation. If there is anything else, just let me know!

**Comment by alessandro-montanari** [comment]
Thanks a lot!
I haven't tried the fix yet but I looked at the README. I think that your way of discriminating between FP and FN is correct but I don't understand why in the figure in the README, the small box in the bottom right corner is counted as FN while the big box on top of it is counted as FP. To me they look like the same error: "there is a predicted BB that matches a GT BB but the class is wrong", isn't it?
Also, is the small box counted twice, as FP and FN at the same time?

In principle I think that it is not necessary to count the FN cases because the term TP + FN (needed for the recall) is basically the number of ground truth BBs. In fact, I was looking at the script used for VOC (https://github.com/marvis/pytorch-yolo2/blob/master/scripts/voc_eval.py) and to me it seems that to compute the recall they simply divide TP by the number of GT BBs (line 194). Does it make sense?

**Comment by MathGaron** [comment]
I will check this in more details later, here is how I understood it (and maybe I am wrong, so do not hesitate to prove me that I am!)
I will refer to the "positive" class as the green, and negative as the red (or other classes).

- TP is when a positive class is retrieved properly
- FN is when a positive GT is not found
That is why the FN from the "negative" class is not calculated in this case
so currently TP + FN is the number of "positive" class GT
The big FP box on top is a bad prediction of positive over negative

the VOC paper is not clear on all this though, unless I missed something. I should check deeper in other implementations though (as you referenced), I think there are many ways to interpret this metric...

And for 
> Also, is the small box counted twice, as FP and FN at the same time?

The FP is on the red prediction, I will update the diagram to make it clear! So the red detection is considered a false positive because it overlaps the green

**Comment by MathGaron** [comment]
The fix has been made previously so I will close this issue.

For the previous message, I will reference to issue #10 , which is testing against VOC official implementation, as the paper is truly ambiguous about some technicalities.
