### ISSUE TITLE
Bounding Box Input

### ISSUE THREAD

**Issue by alrzmshy** [MathGaron/mean_average_precision#7]
Hi and thanks a lot for this repo.

I think there's a mistake in the description of intersect function in bbox_utils.py:

> Bounding boxes use corner notation : [x1, y1, x2, y2]

From your example code and the linked reference, I get the impression that the values are in the x, y, w, h format. Am I mistaken?

Another issue is that, when I tried `intersect(pred_bb1,pred_bb1 ) `  with `pred_bb1=np.array([[0.880688, 0.44609185, 0.95696718, 0.6476958]]) `

I get `array([[ 0.01537818]])`. But, shouldn't the output value be `1` since the arguments are identical?

**Comment by MathGaron** [comment]
Hey,

The description is right, the format used for the bounding box is [x1, y1, x2, y2]. You can also check/use the function show_frame in utils folder to convince yourself!

intersect actually return the area of intersection between the bounding boxes so in your case,
```
(x2-x1) * (y2 -y1) = area
(0.95696718 - 0.880688) * (0.6476958 - 0.44609185) = 0.01537818
```
I think you confound with the Jaccard overlap (intersection over union) of the bounding box, which in the case of the same bounding box should be indeed 1. You can use the function jaccard in the same file to get this result.

That said I will push a change with a more explicit name! Thank you!
