### ISSUE TITLE
installing with pip

### ISSUE THREAD

**Issue by NPetsky** [MathGaron/mean_average_precision#8]
Hi,
I only wanted to mention that I tried installing mean_average_precision with pip and I had to put __init__.py files in every folder and also change setup.py to
 
from distutils.core import setup
**from setuptools import find_packages**

setup(
    name='mean_average_precision',
    version='0.1',
    packages=**find_packages()**,
    url='',
    license='MIT',
    author='Mathieu Garon',
    author_email='mathieugaron91@gmail.com',
    description=''
)

Best regards and thanx for the code!

**Comment by MathGaron** [comment]
Thanks, @NPetsky !
I just pushed this on the repo.
